llms:
  gpt4:
    api_base:
    api_key:
    model_name: gpt-4-0125-preview
  galaxy:
    api_base: http://0.0.0.0:1403/v1
    api_key:
    model_name: galaxy-visual-environment
scenario:
  "i want to initiate a swap with receiver": "initiateSwap"
  "i want to complete the swap with given preimage": "completeSwap"
  "i want to refund the swap": "refundSwap"
  "i want to check the details of a specific swap": "getSwapDetails"
  "i want to see all the swaps": "getAllSwaps"
  "i want to know the status of my swap": "getSwapStatus"
  "i want to start a swap with a specific receiver": "initiateSwap"
  "i want to finish the swap with the provided preimage": "completeSwap"
  "i want to get my money back from the swap": "refundSwap"
  "i want to get information about a particular swap": "getSwapDetails"
  "i want to view all the swaps that have taken place": "getAllSwaps"
  "i want to find out the current status of my swap": "getSwapStatus"
  "i want to create a swap with a certain receiver": "initiateSwap"
  "i want to finalize the swap using the given preimage": "completeSwap"
  "i want to retrieve my funds from the swap": "refundSwap"
  "i want to obtain details about a specific swap": "getSwapDetails"
  "i want to look at all the swaps that have occurred": "getAllSwaps"
  "i want to check the current status of my swap": "getSwapStatus"
  "i want to set up a swap with a designated receiver": "initiateSwap"
  "i want to conclude the swap with the provided preimage": "completeSwap"
  "i want to recover my money from the swap": "refundSwap"
  "i want to acquire information about a particular swap": "getSwapDetails"
  "i want to inspect all the swaps that have happened": "getAllSwaps"
  "i want to verify the current status of my swap": "getSwapStatus"
  "i want to establish a swap with a specific receiver": "initiateSwap"
  "i want to wrap up the swap with the given preimage": "completeSwap"
  "i want to reclaim my funds from the swap": "refundSwap"
  "i want to gather details about a specific swap": "getSwapDetails"
  "i want to review all the swaps that have taken place": "getAllSwaps"
  "i want to confirm the current status of my swap": "getSwapStatus"
  "i want to launch a swap with a particular receiver": "initiateSwap"
  "i want to end the swap with the provided preimage": "completeSwap"
  "i want to retrieve my investment from the swap": "refundSwap"
  "i want to get specifics about a particular swap": "getSwapDetails"
  "i want to examine all the swaps that have been made": "getAllSwaps"
  "i want to ascertain the current status of my swap": "getSwapStatus"
  "i want to kick off a swap with a certain receiver": "initiateSwap"
  "i want to terminate the swap with the given preimage": "completeSwap"
  "i want to get back my money from the swap": "refundSwap"
  "i want to fetch details about a specific swap": "getSwapDetails"
  "i want to scrutinize all the swaps that have transpired": "getAllSwaps"
  "i want to determine the current status of my swap": "getSwapStatus"
  "i want to commence a swap with a specific receiver": "initiateSwap"
  "i want to finalize the swap with the provided preimage": "completeSwap"
  "i want to withdraw my funds from the swap": "refundSwap"
  "i want to procure details about a specific swap": "getSwapDetails"
  "i want to peruse all the swaps that have occurred": "getAllSwaps"
  "i want to validate the current status of my swap": "getSwapStatus"
  "i want to trigger a swap with a particular receiver": "initiateSwap"
  "i want to close the swap with the given preimage": "completeSwap"
  "i want to recoup my money from the swap": "refundSwap"
  "i want to obtain specifics about a particular swap": "getSwapDetails"
  "i want to survey all the swaps that have happened": "getAllSwaps"
  "i want to check the present status of my swap": "getSwapStatus"
  "i want to start a swap transaction with a specific receiver": "initiateSwap"
  "i want to end the swap transaction with the provided preimage": "completeSwap"
  "i want to get a refund from the swap": "refundSwap"
  "i want to get the details of a specific swap transaction": "getSwapDetails"
  "i want to see the list of all swap transactions": "getAllSwaps"
  "i want to know the current status of my swap transaction": "getSwapStatus"
